### PR TITLE
Set date formats to include TZ, for Moment.js

### PR DESCRIPTION
**Pull request by samwilson**
This explicitly adds the timezone to the event form's start and
end date fields, so that it can be correctly read by Moment.js
which otherwise treats the times as being in the browser's
timezone.

There seems to be some discrepencies with how ISO8601 formats
are handled (e.g. the 'T' separating the date and time should be
fine, but it seems to break things).

Bug: T215327

### CODE REVIEW

**Comment by aezell** [comment]
Looks like the Travis build failed but the error is unhelpful. How do we trigger a new build?

**Comment by MaxSem** [comment]
Nah, still fails.

**Comment by samwilson** [comment]
I forgot to update the format in the test.

**Comment by MusikAnimal** [comment]
Thanks! Tested working on my end.

**Pull request merged**
