### PR TITLE
Bump Composer packages

### PR DESCRIPTION
**Pull request by MaxSem**
Hardcode Symfony version to avoid an upgrade to 4.2.

### CODE REVIEW

**Comment by MusikAnimal** [comment]
@MaxSem #148 was merged. Did you want to try upgrading to Symfony 4.2? Or is there another reason we're avoiding it?

**Comment by MaxSem** [comment]
My main concern was that it needs moar testing, but now that you're saying it's fine...

**Comment by MusikAnimal** [comment]
Tests are pretty comprehensive, so I have faith things will be mostly OK if they pass. Symfony also claims everything is backwards-compatible, where you would have received warnings before needing any code changes https://symfony.com/blog/symfony-4-2-curated-new-features As far as I know we've no warnings running on 4.1.8

**Comment by MusikAnimal** [comment]
Everything seems to run fine in 4.2, but indeed there are numerous depredations that look stressful... 4.1.9 it is, for now :)

**Pull request merged**
