### PR TITLE
Remove double quotes from title in CSV file name

### PR DESCRIPTION
**Pull request by MusikAnimal**
See https://github.com/wikimedia/eventmetrics/pull/204#discussion_r261463312

### CODE REVIEW

**Comment by MaxSem** [comment]
Actually, double quotes are reserved on Windows.

**Comment by samwilson** [comment]
Oh right! I didn't know that. Are there other characters we should be avoiding?

**Comment by MaxSem** [comment]
I think I included them all.

**Comment by MusikAnimal** [comment]
Merging per above. Thanks for the help, [Sam & Max](https://en.wikipedia.org/wiki/Sam_%26_Max)!

**Pull request merged**
